name: npm-publish
on:
  push:
    branches:
      - master
jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: |
          cp -r ./config ./publish
          cp ./README.md LICENSE source/*.js ./publish/
          cd ./publish
          npm ci
          npx eslint
          npx semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
